version: 2.1

orbs:
  node: circleci/node@4.5.0

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:12.13.0-browsers
    working_directory: ~/cicd_circleci
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name : Deploy to Beta
          command: |
            if [[ $CODEBUILD_WEBHOOK_EVENT == *"PULL_REQUEST"* ]]; then 
              aws s3 cp index.html s3://circleci-beta-515/index.html --acl public-read 
            fi
      - run:
          name: Deploy to Prod
          command: |
            if [[ $CODEBUILD_WEBHOOK_EVENT == "PULL_REQUEST_MERGED" ]]; then
              aws s3 cp index.html s3://circleci-prod-515/index.html --acl public-read 
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - main
