version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
on:
  pull_request:
    types: [opened, closed, synchronize, merged]

jobs:
  aws_setup: 
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:          
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION_NAME

  deploy_beta:
    executor: aws-cli/default
    steps:
      - run: >-
          aws s3 cp index.html s3://circleci-beta-515/index.html --acl public-read

  deploy_prod:
    executor: aws-cli/default
    steps:
      - checkout
      - run: >-
          aws s3 cp index.html s3://circleci-prod-515/index.html --acl public-read
workflows:
  aws-cli:
    jobs:
      - aws_setup
      - deploy_beta 
      - deploy_prod:
          filters:
            branches:
              only:
                - main
