version: 2.1

orbs:
  node: circleci/node@4.5.0

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14.17.6-browsers
    working_directory: ~/cicd_circleci
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: |
          if [[ $CIRCLE_BRANCH == "main" ]]; then
            npm run deploy-s3-prod
          elif [[ $CIRCLE_BRANCH =~ ^pull/[0-9]+$ ]]; then
            npm run deploy-s3-beta
          else
            echo "Skipping deployment for branch $CIRCLE_BRANCH"
          fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - main
                - /^pull\//
