version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1

on:
  pull_request:
    types: [closed]
    
jobs:
  build_and_deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:          
          aws-access-key-id: $AWS_ACCESS_KEY
          aws-secret-access-key: $AWS_SECRET_KEY
          aws-region: $AWS_REGION_NAME
      - run: >-
            sudo apt-get update && sudo apt-get install -y awscli
workflows:
  aws-cli:
    jobs:
      - deploy_beta:
          requires:
            - hold
      - pre_prod_hold:
          type: approval
          requires:
            - deploy_beta
      - deploy_prod:
          requires:
            - pre_prod_hold
          filters:
            branches:
              only:
                - main