version: 2.1

jobs:
  build_and_deploy:
    working_directory: ~/cicd_circleci
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo test 2
      - run: echo $CODEBUILD_WEBHOOK_EVENT
      - run: |
          if [[ $CODEBUILD_WEBHOOK_EVENT == *"PULL_REQUEST"* ]] ; then
            aws s3 cp index.html s3://codebuild-beta/index.html --acl public-read
          fi
      - deploy_beta:
          requires:
            - approval
      - pre_prod_hold:
          type: approval
          requires:
            - deploy_beta
      - deploy_prod:
          requires:
            - pre_prod_hold
          filters:
            branches:
              only:
                - master

  approval:
    executor: approval/executor
    steps:
      - run:
          name: Request Approval
          command: echo 'Please review this build.'
      - approval/hold

workflows:
  build-and-deploy:
    jobs:
      - build_and_deploy
      - approval:
          filters:
            branches:
              only:
                - master
