version: 2.1

orbs:
  node: circleci/node@4.5.0

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:12.13.0-browsers
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY 
      
    working_directory: ~/cicd_circleci 
    steps:
      - checkout
      - run: |
          sudo apt-get update && sudo apt-get install -y awscli
      - run: npm install
      - run: npm rebuild # optional step to fix any native modules
      - run: npm run build
      - run:
          name : Deploy to Beta
          command: |
            if [[ $CIRCLE_PULL_REQUEST == "" ]]; then 
               /usr/bin/aws s3 cp index.html s3://circleci-beta-515/index.html --acl public-read 
            fi
      - run:
          name: Deploy to Prod
          command: |
            if [[ $CIRCLE_BRANCH == "main" ]]; then 
              /usr/bin/aws s3 cp index.html s3://circleci-prod-515/index.html --acl public-read 
            fi
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - main
