version: 2.1

orbs:
  aws-s3: circleci/aws-cli@3.1

on:
  pull_request:
    types: [closed]
    
jobs:
  create-cf-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:          
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION_NAME
      - run: >-
          aws s3 cp .\index.html s3://circleci-beta-515/index.html --acl public-read
workflows:
  aws-cli:
    jobs:
      - deploy_prod:
          requires:
            - pre_prod_hold
          filters:
            branches:
              only:
                - master
